name: Build

on:
  push:
    branches: [ master ]

jobs:
  build-wasm:
    name: Build the source code into WASM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Build CLN
        run: npm run build-cln

      - name: Build GiNaC
        run: npm run build-ginac

      - name: Build src
        run: npm run build-src

      - name: Build JS library
        run: npm run build-rollup

      - name: Build Typescript types
        run: npm run build-types

      - name: Deploy to 'binaries' branch
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: binaries
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
